//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E4Lisa.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATALOGUE_ENTITE
    {
        public long CAT_Id { get; set; }
        public long ENT_Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime DisplayStartDate { get; set; }
        public System.DateTime DisplayEndDate { get; set; }
    
        public virtual CATALOGUE CATALOGUE { get; set; }
        public virtual ENTITE ENTITE { get; set; }
    }
}
