//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E4Lisa.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ENTITE()
        {
            this.CATALOGUE_ENTITE = new HashSet<CATALOGUE_ENTITE>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Road { get; set; }
        public long CP { get; set; }
        public string City { get; set; }
        public string EMail { get; set; }
        public string Identifier { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATALOGUE_ENTITE> CATALOGUE_ENTITE { get; set; }
        public virtual ENTREPRISE ENTREPRISE { get; set; }
        public virtual MAGASIN MAGASIN { get; set; }
    }
}
