//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E4Lisa.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUIT_ATTRIBUT
    {
        public long PRO_Id { get; set; }
        public long ATT_Id { get; set; }
        public string Valeur { get; set; }
    
        public virtual ATTRIBUT ATTRIBUT { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
