//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E4Lisa.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILISATEUR
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Identifier { get; set; }
        public string Password { get; set; }
        public string Road { get; set; }
        public long CP { get; set; }
        public string City { get; set; }
        public string EMail { get; set; }
        public bool IsTechnician { get; set; }
    }
}
