//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E4Lisa.BDD
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONE
    {
        public long Id { get; set; }
        public long CooX { get; set; }
        public long CooY { get; set; }
        public long Width { get; set; }
        public long Height { get; set; }
        public long PRO_Id { get; set; }
        public long PAG_Id { get; set; }
    
        public virtual PAGE PAGE { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
    }
}
